CREATE TABLE "pre_assessments" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"userId" uuid NOT NULL,
	"workOverwhelmed" integer NOT NULL,
	"concentrationDifficulty" integer NOT NULL,
	"procrastination" integer NOT NULL,
	"irritability" integer NOT NULL,
	"lackAccomplishment" integer NOT NULL,
	"troubleSwitchingOff" integer NOT NULL,
	"feelingDown" integer NOT NULL,
	"losingInterest" integer NOT NULL,
	"feelingAnxious" integer NOT NULL,
	"moodSwings" integer NOT NULL,
	"feelingGuilty" integer NOT NULL,
	"sleepProblems" integer NOT NULL,
	"appetiteChanges" integer NOT NULL,
	"feelingTired" integer NOT NULL,
	"physicalSymptoms" integer NOT NULL,
	"substanceUse" integer NOT NULL,
	"withdrawing" integer NOT NULL,
	"thoughtsOfHarm" integer NOT NULL,
	"lifeNotWorthLiving" integer NOT NULL,
	"worriedAboutStudents" integer NOT NULL,
	"copingMechanisms" jsonb NOT NULL,
	"goals" jsonb NOT NULL,
	"totalScore" integer NOT NULL,
	"riskLevel" text NOT NULL,
	"aiAnalysis" jsonb,
	"personalizedPlan" jsonb,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "pre_assessments" ADD CONSTRAINT "pre_assessments_userId_users_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;